
export type Tag = Exclude<(Tags)['tags'], undefined>[number]; 

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Tags {
  $schema?: string;
  tags?: {
    name: string;
    description?: string;
    showInGmScreen?: boolean;
    hideInPlayerScreen?: boolean;
  }[];
}
